config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets
  devise_for :users

  resources :users do
    member do
      post 'follow'
      delete 'unfollow'
      get :following, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower


  def follow(other_user)
    following << other_user unless self == other_user
  end
  
  def unfollow(other_user)
    following.delete(other_user)
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  

  # validates :role, presence: true, inclusion: { in: %w[influencer fan], message: "%{value} is not a valid role" }

  def influencer?
    role == 'influencer'
  end

  def fan?
    role == 'fan'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def follow
    user = User.find(params[:id])
    current_user.follow(user)
    redirect_to user_path(user)
  end
  
  def unfollow
    user = User.find(params[:id])
    current_user.unfollow(user)
    redirect_to user_path(user)
  end
  
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order(created_at: :desc).page(params[:page]).per(20)
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<p><%= @user.profile %></p>
<%= link_to "フォロー #{@user.following.count} ", following_user_path(@user) %>
<%= link_to "フォロワー #{@user.followers.count} ", followers_user_path(@user) %>

<% unless current_user == @user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'Unfollow', unfollow_user_path(@user), method: :delete, class: "follow-button unfollow" %>
  <% else %>
    <%= link_to 'Follow', follow_user_path(@user), method: :post, class: "follow-button follow" %>
  <% end %>
<% end %>

<h3><%= @user.name %>'s Posts</h3>
<%= render @tweets %>
<%= paginate @tweets %>

app/views/users/show_follow.html.erb
<% @title = @user == current_user ? "You are" : @user.name + " is" %>
<% @title += action_name == "following" ? " following" : "'s followers" %>

<h2><%= @title %></h2>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>